<!DOCTYPE html>
<html>
	<head>
		<title>Tipsy MVC</title>
		<link rel="stylesheet" type="text/css" href="/style.css">
	</head>
	<body>
		<div class="wrapper">
			<header><h1>Tipsy MVC Example</h1></header>
			<nav>
				<a href="/">home</a>
				<a href="/about/bob">bob</a>
				<a href="/about/sue">sue</a>
			</nav>
		    <section>
		        <?=$this->content?>
		    </section>
			<footer>See <a href="https://github.com/arzynik/tipsy/wiki">Documentation</a> or <a href="https://github.com/arzynik/tipsy-mvc">Plugin</a> for more info on <a href="http://tipsy.la">Tipsy</a>.</footer>
		</div>
	</body>
</html>
